In [34]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error

In [35]:
#read in model ready df
df = pd.read_parquet('Resources/model_df.parquet')
df

,"('second_of_day',)","('day_of_year',)","('weekend',)","('holiday',)","('morning_rush',)","('evening rush',)","('prcp',)","('temp',)","('PUx',)","('PUy',)",...,"('PU_Bronx',)","('PU_Brooklyn',)","('PU_Manhattan',)","('PU_Queens',)","('PU_Staten Island',)","('DO_Bronx',)","('DO_Brooklyn',)","('DO_Manhattan',)","('DO_Queens',)","('DO_Staten Island',)"
0,5,1,False,1,0,0,0.0,42.80,-8.213879e+06,4.960411e+06,...,False,False,False,True,False,False,False,True,False,False
1,9,1,False,1,0,0,0.0,42.80,-8.220657e+06,4.992372e+06,...,True,False,False,False,False,True,False,False,False,False
2,33,1,False,1,0,0,0.0,42.80,-8.231953e+06,4.974857e+06,...,False,False,False,True,False,False,True,False,False,False
3,38,1,False,1,0,0,0.0,42.80,-8.212420e+06,4.977409e+06,...,False,False,False,True,False,False,False,False,True,False
4,42,1,False,1,0,0,0.0,42.80,-8.235990e+06,4.975327e+06,...,False,False,True,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6044442,85846,366,False,0,0,0,0.0,48.02,-8.217649e+06,4.988984e+06,...,True,False,False,False,False,True,False,False,False,False
6044443,85864,366,False,0,0,0,0.0,48.02,-8.234034e+06,4.964909e+06,...,False,True,False,False,False,False,True,False,False,False
6044444,85870,366,False,0,0,0,0.0,48.02,-8.236077e+06,4.972248e+06,...,False,False,True,False,False,False,False,True,False,False
6044445,86042,366,False,0,0,0,0.0,48.02,-8.220615e+06,4.964609e+06,...,False,False,False,True,False,False,True,False,False,False
6044446,86273,366,False,0,0,0,0.0,48.02,-8.237813e+06,4.971700e+06,...,False,False,True,False,False,False,False,True,False,False

In [36]:
# fix feature names
df.columns = df.columns.str.replace("'", "")
df.columns = df.columns.str.replace("(", "")
df.columns = df.columns.str.replace(")", "")
df.columns = df.columns.str.replace(",", "")

In [37]:
df

,second_of_day,day_of_year,weekend,holiday,morning_rush,evening rush,prcp,temp,PUx,PUy,...,PU_Bronx,PU_Brooklyn,PU_Manhattan,PU_Queens,PU_Staten Island,DO_Bronx,DO_Brooklyn,DO_Manhattan,DO_Queens,DO_Staten Island
0,5,1,False,1,0,0,0.0,42.80,-8.213879e+06,4.960411e+06,...,False,False,False,True,False,False,False,True,False,False
1,9,1,False,1,0,0,0.0,42.80,-8.220657e+06,4.992372e+06,...,True,False,False,False,False,True,False,False,False,False
2,33,1,False,1,0,0,0.0,42.80,-8.231953e+06,4.974857e+06,...,False,False,False,True,False,False,True,False,False,False
3,38,1,False,1,0,0,0.0,42.80,-8.212420e+06,4.977409e+06,...,False,False,False,True,False,False,False,False,True,False
4,42,1,False,1,0,0,0.0,42.80,-8.235990e+06,4.975327e+06,...,False,False,True,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6044442,85846,366,False,0,0,0,0.0,48.02,-8.217649e+06,4.988984e+06,...,True,False,False,False,False,True,False,False,False,False
6044443,85864,366,False,0,0,0,0.0,48.02,-8.234034e+06,4.964909e+06,...,False,True,False,False,False,False,True,False,False,False
6044444,85870,366,False,0,0,0,0.0,48.02,-8.236077e+06,4.972248e+06,...,False,False,True,False,False,False,False,True,False,False
6044445,86042,366,False,0,0,0,0.0,48.02,-8.220615e+06,4.964609e+06,...,False,False,False,True,False,False,True,False,False,False
6044446,86273,366,False,0,0,0,0.0,48.02,-8.237813e+06,4.971700e+06,...,False,False,True,False,False,False,False,True,False,False

In [38]:
# check dtypes
df.dtypes

second_of_day         int32
day_of_year           int32
weekend                bool
holiday               int64
morning_rush          int32
evening rush          int32
prcp                float64
temp                float64
PUx                 float64
PUy                 float64
DOx                 float64
DOy                 float64
distance            float64
durationsec         float64
fare                float64
tolls               float64
airport             float64
congestion          float64
total               float64
class                 int64
PU_Bronx               bool
PU_Brooklyn            bool
PU_Manhattan           bool
PU_Queens              bool
PU_Staten Island       bool
DO_Bronx               bool
DO_Brooklyn            bool
DO_Manhattan           bool
DO_Queens              bool
DO_Staten Island       bool
dtype: object

In [39]:
#knr testing
'''
train_scores = []
test_scores = []
for k in range(1, 20, 2):
    knr = KNeighborsRegressor(n_neighbors=k)
    knr.fit(X_train_scaled, y_train)
    train_score = knr.score(X_train_scaled, y_train)
    test_score = knr.score(X_test_scaled, y_test)
    train_scores.append(train_score)
    test_scores.append(test_score)
    print(f"k: {k}, Train/Test Score: {train_score:.3f}/{test_score:.3f}")
    
plt.plot(range(1, 20, 2), train_scores, marker='o', label="training scores")
plt.plot(range(1, 20, 2), test_scores, marker="x", label="testing scores")
plt.xlabel("k neighbors")
plt.ylabel("accuracy score")
plt.legend()
plt.show()
'''

'\ntrain_scores = []\ntest_scores = []\nfor k in range(1, 20, 2):\n    knr = KNeighborsRegressor(n_neighbors=k)\n    knr.fit(X_train_scaled, y_train)\n    train_score = knr.score(X_train_scaled, y_train)\n    test_score = knr.score(X_test_scaled, y_test)\n    train_scores.append(train_score)\n    test_scores.append(test_score)\n    print(f"k: {k}, Train/Test Score: {train_score:.3f}/{test_score:.3f}")\n    \nplt.plot(range(1, 20, 2), train_scores, marker=\'o\', label="training scores")\nplt.plot(range(1, 20, 2), test_scores, marker="x", label="testing scores")\nplt.xlabel("k neighbors")\nplt.ylabel("accuracy score")\nplt.legend()\nplt.show()\n'

In [40]:
df.columns

Index(['second_of_day', 'day_of_year', 'weekend', 'holiday', 'morning_rush',
       'evening rush', 'prcp', 'temp', 'PUx', 'PUy', 'DOx', 'DOy', 'distance',
       'durationsec', 'fare', 'tolls', 'airport', 'congestion', 'total',
       'class', 'PU_Bronx', 'PU_Brooklyn', 'PU_Manhattan', 'PU_Queens',
       'PU_Staten Island', 'DO_Bronx', 'DO_Brooklyn', 'DO_Manhattan',
       'DO_Queens', 'DO_Staten Island'],
      dtype='object')

In [41]:
#change this range to filter days of data

df_filter_range = range(1, 31)

filter_mask = df['day_of_year'].isin(df_filter_range)

df_filtered = df[filter_mask]

df_filtered

,second_of_day,day_of_year,weekend,holiday,morning_rush,evening rush,prcp,temp,PUx,PUy,...,PU_Bronx,PU_Brooklyn,PU_Manhattan,PU_Queens,PU_Staten Island,DO_Bronx,DO_Brooklyn,DO_Manhattan,DO_Queens,DO_Staten Island
0,5,1,False,1,0,0,0.0,42.8,-8.213879e+06,4.960411e+06,...,False,False,False,True,False,False,False,True,False,False
1,9,1,False,1,0,0,0.0,42.8,-8.220657e+06,4.992372e+06,...,True,False,False,False,False,True,False,False,False,False
2,33,1,False,1,0,0,0.0,42.8,-8.231953e+06,4.974857e+06,...,False,False,False,True,False,False,True,False,False,False
3,38,1,False,1,0,0,0.0,42.8,-8.212420e+06,4.977409e+06,...,False,False,False,True,False,False,False,False,True,False
4,42,1,False,1,0,0,0.0,42.8,-8.235990e+06,4.975327e+06,...,False,False,True,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474329,86353,30,False,0,0,0,0.0,37.4,-8.231792e+06,4.962136e+06,...,False,True,False,False,False,False,True,False,False,False
474330,86362,30,False,0,0,0,0.0,37.4,-8.220657e+06,4.992372e+06,...,True,False,False,False,False,True,False,False,False,False
474331,86376,30,False,0,0,0,0.0,37.4,-8.231020e+06,4.952350e+06,...,False,True,False,False,False,False,True,False,False,False
474332,86386,30,False,0,0,0,0.0,37.4,-8.234352e+06,4.975524e+06,...,False,False,True,False,False,False,False,True,False,False
474333,86395,30,False,0,0,0,0.0,37.4,-8.235586e+06,4.979010e+06,...,False,False,True,False,False,False,True,False,False,False

In [42]:
#change this to sample filter df

df_filtered_2 = df.sample(frac=0.10)

df_filtered_2

,second_of_day,day_of_year,weekend,holiday,morning_rush,evening rush,prcp,temp,PUx,PUy,...,PU_Bronx,PU_Brooklyn,PU_Manhattan,PU_Queens,PU_Staten Island,DO_Bronx,DO_Brooklyn,DO_Manhattan,DO_Queens,DO_Staten Island
996657,81764,61,False,0,0,0,0.0,41.00,-8.237633e+06,4.975305e+06,...,False,False,True,False,False,False,False,True,False,False
4531470,48459,278,False,0,0,0,0.0,64.94,-8.222992e+06,4.977499e+06,...,False,False,False,True,False,False,False,True,False,False
2625381,59827,157,False,0,0,1,0.0,77.00,-8.213879e+06,4.960411e+06,...,False,False,False,True,False,False,False,False,False,False
3385938,18609,205,False,0,0,0,0.0,73.40,-8.228482e+06,4.968269e+06,...,False,True,False,False,False,False,True,False,False,False
3295287,44499,199,False,0,0,0,0.0,78.08,-8.236394e+06,4.976052e+06,...,False,False,True,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4686079,65372,287,True,0,0,0,0.0,71.96,-8.226023e+06,4.994144e+06,...,True,False,False,False,False,False,False,True,False,False
3862803,36625,236,False,0,0,0,0.0,66.92,-8.233149e+06,4.978027e+06,...,False,False,True,False,False,False,False,True,False,False
422804,65633,27,True,0,0,0,0.0,46.04,-8.230884e+06,4.964444e+06,...,False,True,False,False,False,False,True,False,False,False
3529449,43530,214,False,0,0,0,0.0,78.98,-8.232220e+06,4.983524e+06,...,False,False,True,False,False,False,False,True,False,False
2165178,41390,109,False,0,0,0,0.3,46.40,-8.232604e+06,4.977812e+06,...,False,False,True,False,False,False,False,True,False,False

In [43]:
#drop leaky columns
df_filtered = df_filtered.drop(['fare', 'durationsec'], axis=1)

In [44]:
#drop leaky columns
df_filtered_2 = df_filtered_2.drop(['fare','durationsec'], axis=1)

In [45]:
#prep for models
X_2 = df_filtered_2.copy()
X_2 = X_2.drop('total', axis=1)

y_2 = df_filtered_2['total'].values.reshape(-1,1)

In [46]:
#traintestsplit
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X_2, y_2, random_state=29)

In [47]:
# knr training and testing score

'''
knr2 = KNeighborsRegressor(n_neighbors=5)
knr2.fit(X_train_2, y_train_2)
print(knr2.score(X_train_2, y_train_2))
print(knr2.score(X_test_2, y_test_2))

'''

'\nknr2 = KNeighborsRegressor(n_neighbors=5)\nknr2.fit(X_train_2, y_train_2)\nprint(knr2.score(X_train_2, y_train_2))\nprint(knr2.score(X_test_2, y_test_2))\n\n'

In [48]:
#knr mae
'''
y_predicted = knr2.predict(X_test_2)

mae = mean_absolute_error(y_test_2, y_predicted)

print(mae)
'''

'\ny_predicted = knr2.predict(X_test_2)\n\nmae = mean_absolute_error(y_test_2, y_predicted)\n\nprint(mae)\n'

In [49]:
# testing the models on each individual service

uber_df = df_filtered[(df_filtered['class'] == 1) & (df['total'] > 0)]
taxi_df = df_filtered[(df_filtered['class'] == 0) & (df['total'] > 0)]
lyft_df = df_filtered[(df_filtered['class'] == 2) & (df['total'] > 0)]

C:\Users\Nik\AppData\Local\Temp\ipykernel_16440\3344396972.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  uber_df = df_filtered[(df_filtered['class'] == 1) & (df['total'] > 0)]
C:\Users\Nik\AppData\Local\Temp\ipykernel_16440\3344396972.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  taxi_df = df_filtered[(df_filtered['class'] == 0) & (df['total'] > 0)]
C:\Users\Nik\AppData\Local\Temp\ipykernel_16440\3344396972.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  lyft_df = df_filtered[(df_filtered['class'] == 2) & (df['total'] > 0)]

In [50]:
uber_df

,second_of_day,day_of_year,weekend,holiday,morning_rush,evening rush,prcp,temp,PUx,PUy,...,PU_Bronx,PU_Brooklyn,PU_Manhattan,PU_Queens,PU_Staten Island,DO_Bronx,DO_Brooklyn,DO_Manhattan,DO_Queens,DO_Staten Island
1,9,1,False,1,0,0,0.0,42.8,-8.220657e+06,4.992372e+06,...,True,False,False,False,False,True,False,False,False,False
8,75,1,False,1,0,0,0.0,42.8,-8.221833e+06,4.988439e+06,...,True,False,False,False,False,True,False,False,False,False
13,162,1,False,1,0,0,0.0,42.8,-8.236580e+06,4.974117e+06,...,False,False,True,False,False,False,False,True,False,False
19,202,1,False,1,0,0,0.0,42.8,-8.236394e+06,4.976052e+06,...,False,False,True,False,False,False,False,True,False,False
27,257,1,False,1,0,0,0.0,42.8,-8.236601e+06,4.964303e+06,...,False,True,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474314,86265,30,False,0,0,0,0.0,37.4,-8.236629e+06,4.970973e+06,...,False,False,True,False,False,False,False,True,False,False
474315,86266,30,False,0,0,0,0.0,37.4,-8.209171e+06,4.964830e+06,...,False,False,False,True,False,False,False,False,True,False
474318,86274,30,False,0,0,0,0.0,37.4,-8.226770e+06,4.971716e+06,...,False,False,False,True,False,False,True,False,False,False
474331,86376,30,False,0,0,0,0.0,37.4,-8.231020e+06,4.952350e+06,...,False,True,False,False,False,False,True,False,False,False
474333,86395,30,False,0,0,0,0.0,37.4,-8.235586e+06,4.979010e+06,...,False,False,True,False,False,False,True,False,False,False

In [51]:
# uber df prep
X = uber_df.copy()
X = X.drop('total', axis=1)

y = uber_df['total'].values.reshape(-1,1)

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=29)

In [53]:
# knr and scores on all services dataset
knr = KNeighborsRegressor(n_neighbors=5)
knr.fit(X_train_2, y_train_2)
print('Train/Test r-2:')
print(knr.score(X_train_2, y_train_2))
print(knr.score(X_test_2, y_test_2))

Train/Test r-2:
0.8483567173073521
0.7778962901835512

In [54]:
# mae on all services knr
y_predicted = knr.predict(X_test)

mae = mean_absolute_error(y_test, y_predicted)
print('Mean abs Error:')
print(mae)

Mean abs Error:
5.804748975357992

In [55]:
# knr and scores on uber dataset
knr = KNeighborsRegressor(n_neighbors=5)
knr.fit(X_train, y_train)
print('Uber Train/Test r-2:')
print(knr.score(X_train, y_train))
print(knr.score(X_test, y_test))

Uber Train/Test r-2:
0.8341346037000956
0.7440731435625882

In [56]:
# mae for uber knr
y_predicted = knr.predict(X_test)

mae = mean_absolute_error(y_test, y_predicted)
print('Uber Mean abs Error:')
print(mae)

Uber Mean abs Error:
5.58257708849871

In [57]:
# prep lift data
X = lyft_df.copy()
X = X.drop('total', axis=1)

y = lyft_df['total'].values.reshape(-1,1)

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=29)

In [59]:
# knr and scores for lyft dataset
knr = KNeighborsRegressor(n_neighbors=5)
knr.fit(X_train, y_train)
print('Lyft Train/Test r-2:')
print(knr.score(X_train, y_train))
print(knr.score(X_test, y_test))

Lyft Train/Test r-2:
0.850907617570499
0.7608914152478187

In [60]:
#mae for lyft knr
y_predicted = knr.predict(X_test)

mae = mean_absolute_error(y_test, y_predicted)
print('Lyft Mean abs Error:')
print(mae)

Lyft Mean abs Error:
4.77001348129127

In [61]:
# prep taxi data
X = taxi_df.copy()
X = X.drop('total', axis=1)

y = taxi_df['total'].values.reshape(-1,1)

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=29)

In [63]:
#knr and scores for taxi data
knr = KNeighborsRegressor(n_neighbors=5)
knr.fit(X_train, y_train)
print('Taxi Train/Test r-2:')
print(knr.score(X_train, y_train))
print(knr.score(X_test, y_test))

Taxi Train/Test r-2:
0.894055191677226
0.8327309579667113

In [64]:
# mae for taxi knr
y_predicted = knr.predict(X_test)

mae = mean_absolute_error(y_test, y_predicted)
print('Taxi Mean abs Error:')
print(mae)

Taxi Mean abs Error:
4.606239167914983